server:
  port: 8080

spring:
  datasource:
    username: user
    password: password
    url: jdbc:mysql://localhost:3306/search_engine?useSSL=false&requireSSL=false&allowPublicKeyRetrieval=true
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    hibernate:
        ddl-auto: create-drop
    show-sql: true

indexing-settings:
  sites:
    - url: https://www.playback.ru
      name: PlayBack.Ru
    - url: https://www.lutherancathedral.ru
      name: Lutherancathedral.ru
    - url: https://nikoartgallery.com
      name: Nikoartgallery.com
  userAgent: Mozilla/5.0 (Windows NT 6.1; rv:98.0) Gecko/20100101 Firefox/98.0
  referrer: http://google.com